### ISSUE TITLE
Deployed to liferay directory, 404 not found

### ISSUE THREAD

**Issue by MarcoPortillo** [izaera/liferay-js-toolkit-showcase#1]
Hi.

I downloaded the entire project and I deployed it to my liferay server, it appears this error:

`2019-10-07 14:54:19.916 WARN  [http-nio-8080-exec-2][code_jsp:?] {code="404", msg="Not Found", uri=/o/liferay-js-toolkit-showcase/css/styles.css}`

I checked my chrome resources and it does not appear under /o/ directory but I can added it normally from the panel

**Comment by izaera** [comment]
I have updated the `loaders` branch. That, I think, should fix your problem.
