### ISSUE TITLE
Test csv data

### ISSUE THREAD

**Issue by allen-ziegenfus** [izaera/liferay-js-toolkit-showcase#3]
@izaera   I tried the react modules out but I don't see any data, is there a test csv file that I missed? Thanks

![image](https://user-images.githubusercontent.com/16581685/91183553-391ca580-e6b1-11ea-9de9-c4fb11120687.png)

**Comment by izaera** [comment]
https://github.com/izaera/liferay-js-toolkit-showcase/commit/9710c75b6656835c05c5909f5515921c9b56a647
